config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  get 'subjects/index'
  

  devise_for :users
  resources :dashboard
  resources :subjects
  resources :profiles
  	
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	validates :user_id, presence: true, uniqueness: {message: "already created one."}
	validates :name, presence: true, length: { maximum: 50 }
	# The validation below is for uniqueness (no duplicates) on a model attribute.
	validates :initial, presence: true, length: { maximum: 1 }
	validates :phrase, presence: true
	validates :education, presence: true
	validates :certification, presence: true
	validates :experience, presence: true
	validates :rate, presence: true, length: { maximum: 3 }
	validates :zip, presence: true, length: { maximum: 5 }

    
	has_and_belongs_to_many :subjects
	belongs_to :user
    geocoded_by :zip
    after_validation :geocode, :if => :zip_changed?
    #reverse_geocoded_by :latitude, :longitude
    #fter_validation :reverse_geocode


	has_attached_file :avatar, styles: { small: "160x160#"}, :default_url => ActionController::Base.helpers.asset_path('missing.png')
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

	

    searchable do
    	text :subject_search
  		latlon(:location) { Sunspot::Util::Coordinates.new(self.latitude, self.longitude) }
        string :search_near
    end

    
    def search_near
    	self.zip
    end

    def subject_search
    	subjects.map { |subject| subject.title }
    end


end

app/models/subject.rb
class Subject < ActiveRecord::Base
	
	has_and_belongs_to_many :profiles

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_one :profile


  
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :authenticate_user!




	def index
		@profile = Profile.find_by(params[:id])
	end



	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if user_signed_in?
			redirect_to controller:'dashboard', action: 'index'
		else
			redirect_to controller:'profiles', action: 'index'
		end
	end

	

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  respond_to :html, :json
 
    def index
      @search = Profile.search do 
        fulltext params[:subject_search]
        with(:location).in_radius(*Geocoder.coordinates(params[:search_near]), 10) if params[:search_near].present?
      end
      @profiles = @search.results
    end


    def new
    	@profile = Profile.new 
    end

    def show
      @profile = Profile.find(params[:id])
      profile = Profile.find(params[:id])
      @subject = profile.subjects
      
    end
      

    def create
      @profile = Profile.new(profile_params)
      @profile.user = current_user
      if @profile.save
        @profile.subjects << subject
      	flash[:success] = "Profile successfully created."
      	redirect_to @profile
      else
      	render 'new'
      end
    end

    def edit
      @profile = Profile.find(params[:id])
    end

    def update
      @profile = Profile.find(params[:id])
      if @profile.update_attributes(profile_params)
        flash[:success] = "Profile updated"
        redirect_to @profile
      else
        render 'edit'
      end
    end


  

    private

      
         def subject
          @subject = Subject.where("id = ?", params[subject_ids: []])
         end
      

         def profile_params
      	  params.require(:profile).permit(:avatar, :name, :initial, :phrase, :education, :certification, :experience, :rate, :zip, :latitude, :longitude, subject_ids: [])
         end

end
 

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
	respond_to :html, :json
	

 def index
    @subject = Subject.all
    respond_with @subject
  end

  def new
  	@subject = Subject.new 
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def create
  @subject = Subject.new(subject_params)
    if @subject.save
    	flash[:success] = "Subject successfully created."
    	redirect_to @subject
    else
    	render 'new'
    end
  end

   private

      

      def subject_params
    	  params.require(:subject).permit(:heading, :title)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Inspired Higher Learning"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper

	def profile
		@profile.user
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper

	
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/dashboard/index.html.erb
<% provide(:title, "Dashboard") %>
<h1 style="margin-top:50px;">Dashboard for Profile Management</h1><br />


<h2 style="text-align:center;">Teacher application progress</h2>

<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 75%">
    75%
  </div>
</div>
</br ><br />


<div style="margin-left: 15px;">
    <div class="row">
        	<div class="col-md-3">

            <%= link_to image_tag("bgcheck.png", alt: "Background Check"),
                    '#' %>
          </div>
        	
          <div class="col-md-3">

            <%= link_to image_tag("application.png", alt: "Application"), '#' %>
          </div>

          <div class="col-md-3">

            <%= link_to image_tag("payment.png", alt: "Payment Info"), '#' %>
          </div>

          <div class="col-md-3">
              <% if current_user.profile %>
            
              <%= link_to image_tag("edit_img.png", alt: "edit Profile"), edit_profile_path(current_user) %>
              
              <% else %>
              
              <%= link_to image_tag("create_img.png", alt: "Create Profile"), new_profile_path %>
       
              <% end %>
          </div>

      </div>
</div>

app/views/home/index.html.erb
<% provide(:title, "") %>
<div class="center jumbotron">
  <h1>Welcome to Inspired Higher Learning</h1>

  <h2>
    This is the home page for the
    <a href="http://www.i-hl.net/">Tutoring Resource</a>
    For Certified Teachers.
  </h2>

  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
       <a href="http://www.i-hl.net/">Inspired Higher Learning</a>
    by <a href="http://www.i-hl.net/about.htm">Cristee Kim</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "IHL", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", '#' %></li>
        <li><%= link_to "About", '#' %></li>
        <li><%= link_to "Contact", '#' %></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if (current_user.profile).nil? %>
              <li><%= link_to "Create Profile", new_profile_path %> </li>
              <% else %>
              <li><%= link_to "Profile", (current_user.profile) %></li>
              <% end %>
              <li><%= link_to "Settings", dashboard_index_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in",  new_user_session_path, {:style => 'color: #5EB7FF'} %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
       <%= render 'layouts/header' %>
       <div class="container">
       <% flash.each do |name, msg| %>
       <%= content_tag(:div, msg, class: "alert alert-info") %>
       <% end %>
	
		<% if user_signed_in? %>
		<div class="user">Signed in as <%= current_user.email %></div>
		<% end %>



<%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/profiles/_profiles.html.erb
<div class="whole">
        <div class="clickable">
          <a href="#" class="fill-div"></a>
            <% @profiles.each do |p| %>
            <div class="box1">
              <div class="p_pic"><%= image_tag p.avatar.url(:small) %></div>
            </div>

            <div class="box2">
                  <div class="name"><%= p.name %> <%= p.initial %>.  <span class="geo"><%= p.zip %></span> </div>
                  <div class="mid_2"><%= p.phrase %></div>

                  <div class="mid_3">
                    <%= truncate(p.experience, :length => 160, :separator => ' ' ) %> <%= link_to 'read more', @profile %>
                  </div>
                  <div class="mid_4">Offering <%= p.subjects.count %> Subjects</div>
            </div>

            <div class="box3">
                  <div class="bx3sub1">$<%= p.rate %><span class="p_rate">/per hour</span></div>
                  <div class="bx3sub2">Rating</div>
                  <div class="bx3sub3"><%= link_to "View Tutor", @profile, class: "btn btn-default" %></div>
            </div>

            <% end %>
       </div>
</div>

app/views/profiles/edit.html.erb
<% provide(:title, 'edit Profile') %>
<h1>Edit Profile</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @profile, :html => { :multipart => true } do |f| %>
		<%= render 'shared/error_messages' %>
		  <%= f.label :avatar, "Upload Profile Picture" %>
		  <%= f.file_field :avatar, class: 'form-control' %>

		  <%= f.label :name, "First Name" %>
		  <%= f.text_field :name, class: 'form-control' %>

		  <%= f.label :initial, "Last Initial" %>
		  <%= f.text_field :initial, class: 'form-control' %>
		  
		  <%= f.label :phrase, "Catchy Phrase" %>
		  <em>( For ex: Very organized and persistent. )</em>
		  <%= f.text_field :phrase, class: 'form-control' %>

		  <%= f.label :education %>
		  <%= f.text_field :education, class: 'form-control' %>

		  <%= f.label :certification %>
		  <%= f.text_field :certification, class: 'form-control' %>

          <em>( You can select all subjects that apply. )</em>
          <div>
          
          <%= f.collection_select :subject_ids, Subject.all, :id, :title, {include_blank: true}, id: "performer", data: { placeholder: "Choose subject(s)" }, multiple: true %>
          </div><br>
		  <%= f.label :experience, "Teaching Experience" %>
		  <%= f.text_area :experience, class: 'form-control' %>

		  <%= f.label :zip, "Zip Code" %>
		  <%= f.text_field :zip, class: 'form-control' %>
          
		  <%= f.label :rate, "Hourly Rate" %>
		  <%= f.text_field :rate, class: 'form-control' %>
          
		  <%= f.submit "Save changes", class: "btn btn-primary" %>
		  <%= link_to ("Cancel"), dashboard_index_path(current_user) %>
		  <% end %>
		</div>
	</div>


<script type="text/javascript"> $(document).ready(function() { 
$('select#performer').select2({
placeholder: "Choose your subjects",
allowClear: true,
width: '100%'
});
});
</script> 

app/views/profiles/index.html.erb
<% provide(:title, 'All Tutors') %>
<h1>All Tutors</h1>


<div class="row">
	<div class="col-xs-6 col-md-4">
		side bar content on this side.
	</div>


    <div class="col-xs-12 col-sm-6 col-md-8">
	   	 
<%= form_tag profiles_path, method: :get do %>
<p>
    
	<p>Enter Zip:</p>
	<%= text_field_tag :search_near, params[:search_near] %>
	<p>Enter Subject:</p>
	<%= text_field_tag :subject_search, params[:subject_search] %>
	

	<%= submit_tag "Search", name: nil %>
</p>
<% end %>

	<% for profile in @profiles do %>
	<ul style="list-style:none;">
		<li> <h4><%= profile.user.email %></h4></li>
		<li> <%= link_to profile.name, profile %> </li>
		<li> <%= profile.zip %></li>
		<li><b>($<%= profile.rate %>)</b></li>
		 <% profile.subjects.each do |s| %> 
		 <li> <%= s.title %> </li>
		 <% end %>
	</ul>
	<% end %>









    </div>

</div>


	

    
   

app/views/profiles/new.html.erb
<% provide(:title, 'Create Profile') %>
<h1>Create Profile</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @profile, :html => { :multipart => true } do |f| %>
		<%= render 'shared/error_messages' %>
		  <%= f.label :avatar, "Upload Profile Picture" %>
		  <%= f.file_field :avatar, class: 'form-control' %>

		  <%= f.label :name, "First Name" %>
		  <%= f.text_field :name, class: 'form-control' %>

		  <%= f.label :initial, "Last Initial" %>
		  <%= f.text_field :initial, class: 'form-control' %>
		  
		  <%= f.label :phrase, "Catchy Phrase" %>
		  <em>( For ex: Very organized and persistent. )</em>
		  <%= f.text_field :phrase, class: 'form-control' %>

		  <%= f.label :education %>
		  <%= f.text_field :education, class: 'form-control' %>

		  <%= f.label :certification %>
		  <%= f.text_field :certification, class: 'form-control' %>

          <em>( You can select all subjects that apply. )</em>
          <div>
          
          <%= f.collection_select :subject_ids, Subject.all, :id, :title, {include_blank: true}, id: "performer", data: { placeholder: "Choose subject(s)" }, multiple: true %>
          </div><br>
		  <%= f.label :experience, "Teaching Experience" %>
		  <%= f.text_area :experience, class: 'form-control' %>

		  <%= f.label :rate, "Hourly Rate" %>
		  <%= f.text_field :rate, class: 'form-control' %>

		  <%= f.label :zip, "Zip Code" %>
		  <%= f.text_field :zip, class: 'form-control' %>

		  <%= f.hidden_field :latitude, class: 'form-control' %>

		  <%= f.hidden_field :longitude, class: 'form-control' %>
          
		  
          
		  <%= f.submit "Create my profile", class: "btn btn-primary" %>
		  <% end %>
		</div>
	</div>


<script type="text/javascript"> $(document).ready(function() { 
$('select#performer').select2({
placeholder: "Choose your subjects",
allowClear: true,
width: '100%'
});
});
</script> 

app/views/profiles/show.html.erb
<% provide(:title, @profile.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <p> <b><%= @profile.name %> <%= @profile.initial %>.</b> (ID : <%= @profile.id %>)</p>
      <%= image_tag @profile.avatar.url(:small) %>
      <p> <b>Catchy Phrase:</b> <%= @profile.phrase %></p>
    
      <li style = "list-style: none"> <b>Education:</b>       <%= @profile.education %></li>
      <li style = "list-style: none"> <b>Certification:</b>   <%= @profile.certification %></li>
      <li style = "list-style: none"> <b>Experience:</b>      <%= @profile.experience %></li>
      <li style = "list-style: none"> <b>Hourly Rate:</b>     <%= @profile.rate %></li>
      <hr>
The <b>Subject:</b> field is what is used to run the search queries.
<hr>
      <li style = "list-style: none"> <u><b>Subject(s):</b></u> 
         
        <% @subject.each do |s| %>
        <li style = "list-style: none"><%= s.title %></li>
        <% end %>
      </li><br>
      
    
     <p><%= link_to 'All Profiles', {:action => :index}  %> </p>
      
    </section>
  </aside>
</div>

app/views/shared/_error_messages.html.erb
<% if @profile.errors.any? %>
    <div id="error_explanation">
	    <div class="alert alert-danger">
		The form contains <%= pluralize(@profile.errors.count, "error") %>.
	    </div>
	    <ul>
		<% @profile.errors.full_messages.each do |msg| %>
		    <li><%= msg %></li>
		<% end %>
	    </ul>
    </div>
<% end %>

app/views/shared/_error_sub_messages.html.erb
<% if @subject.errors.any? %>
    <div id="error_explanation">
	    <div class="alert alert-danger">
		The form contains <%= pluralize(@profile.errors.count, "error") %>.
	    </div>
	    <ul>
		<% @subjects.errors.full_messages.each do |msg| %>
		    <li><%= msg %></li>
		<% end %>
	    </ul>
    </div>
<% end %>

app/views/subjects/index.html.erb
<h1>Subjects#index</h1>
<script>
$(document).ready(function() { $("#monkey").select2(); });
</script>

<h2> Sample Data </h2>

<% @subject.each do |s|%>
<li> <%= s.id %> | <%= s.heading %> | <%= s.title %> </li>
<% end %>

 <%= link_to ("Create Subject"), 'new' %>


<br><br><br><br><br><br>

<em>Please select all subjects that apply.</em>
<div>
<%= select_tag "subject_id[]", options_from_collection_for_select(@subject, "id", "title"), include_blank: true, id: "performer", data: { placeholder: "Choose you subjects" }, multiple: true %></div>





<script type="text/javascript"> $(document).ready(function() { 
$('select#performer').select2({
placeholder: "Choose your subjects",
allowClear: true,
width: '30%'
});
});
</script> 

app/views/subjects/new.html.erb
<% provide(:title, 'Create Subject') %>
<h1>Create Subjects</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@subject) do |f| %>
		<%= render 'shared/error_sub_messages' %>
		  <%= f.label :heading %>
		  <%= f.text_field :heading, class: 'form-control' %>

		  <%= f.label :title %>
		  <%= f.text_field :title, class: 'form-control' %>

		  <%= f.submit "Create Subject", class: "btn btn-primary" %>
		  <% end %>
		</div>
	</div>

app/views/subjects/show.html.erb
<% provide(:title, 'All Subjects') %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <br><br><br>
     <p> <%= @subject.heading %> | <%= @subject.title %></p>

     <%= link_to ("All Subjects"), 'index' %>
      
    </section>
  </aside>
</div>